### ISSUE TITLE
Capacitor 3 - Feature not available on this platform / device - Android

### ISSUE THREAD

**Issue by dhwalin** [jepiqueau/react-data-storage-sqlite-hook#1]
After updating to Capacitor 3, this error is occurring on android device. I have not checked yet on iOS. 

```
Feature not available on this platform / device
```

**Comment by merganon** [comment]
Seems like the plugin was updated to Capacitor 3: https://github.com/jepiqueau/react-data-storage-sqlite-hook/commit/bbca06bc5ef7a8ce7f5a4f66958e02a89093e69c

Can you check if the error still occurs? @dhwalin

**Comment by dhwalin** [comment]
It is working now. Yes. Thank you.
